name: 🐛 Bug report
description: Create a report to help us squash bugs!
title: "[Bug]: "
labels: ["T:Bug"]
body:
  - type: markdown
    attributes:
      value: |
        # Guidelines for Submitting a Bug Report

        _Thanks for taking the time to fill out this bug report!
        Before smashing the submit button please review the template.
        Please also ensure that this is not a duplicate issue :)_

        ## 🚨 IMPORTANT Notes on Security

        _Prior to opening a bug report, check if it affects one of the core modules
        and if its elegible for a bug bounty on `SECURITY.md`. Bugs that are not submitted
        through the appropriate channels won't receive any bounty._

  - type: textarea
    id: summary
    attributes:
      label: Summary of the Bug/Defect
      description: Concisely describe the issue. What did was expected?
      placeholder: Tell us what occured versus what you expected.
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: How to reproduce?
      description: Please describe how to reproduce the bug/defect.
      placeholder: What commands in order should someone run to reproduce the defect?
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: If applicable, specify the version you're using
      placeholder: v1.0.0, v0.50.10-mantrachain-v1.0.0, main, etc.
    validations:
      required: true