# Staticmajor: Static analyzer to catch leaking resources & other bad code patterns
name: Detect leaking resources and bad code patterns
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release/**
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - "**/go.mod"
      - "**/go.sum"
  workflow_dispatch:

jobs:
  run_staticmajor:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Staticmajor action
        id: staticmajor
#        uses: orijtech/staticmajor-action@main
        run: echo "re-enable later"
        with:
          packages: ./...
          resleak: true
          structslop: false
          tests: false
